[project]
name = "filmscan-studio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jarogumulec", email = "29793471+jarogumulec@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "pillow>=12.3.0",
    "pillow-heif>=1.7.0",
    "pydantic>=2.13.5",
    "pyside6>=6.11.2",
    "tifffile>=2025.6.11",
]

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-qt>=4.5.0",
]

[project.scripts]
filmscan-studio = "filmscan_studio.__main__:main"
filmscan-develop = "filmscan_studio.developer.__main__:main"
filmscan-develop-gui = "filmscan_studio.developer.gui:main"
filmscan-annotate = "filmscan_studio.annotator.gui:main"
